### ISSUE TITLE
ABOUT YOUR PURPOSE!

### ISSUE THREAD

**Issue by kyzhouhzau** [YaoXinZhi/Plant-traits-Ontology-with-phrase-embedding#1]
i am not clear with your purpose. Can you clarify it clearly in the README.

**Comment by YaoXinZhi** [comment]
I'm just backing up the code，😡😡😡 391166792 邮箱：391166792@qq.com 签名由 网易邮箱大师 定制 On 05/11/2020 22:06, Kaiyinzhou wrote: i am not clear with your purpose. Can you clarify it clearly in the README. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ergazee** [comment]
Yeah, kyzhouhzau is right, backing up also need a good README. 😜

**Comment by YaoXinZhi** [comment]
hhh, ok, i’ll see😲😲
